--- This was generated with the following google sheets document https://docs.google.com/spreadsheets/d/1wD75vRdrGCnJHZEK4hdDMmnXnVmHhCvYGbdVosiZSAk/edit#gid=0
--- This sheet contains most of the variations of fund names for the years, but the regex covers more variations than are present in the sheet.

--- Cell X94 in this sheet contains all the regex patterns used for these funds in a julia regex string format

--- we recommend using https://regex101.com/ to verify and test the regex if you decide to change it

--- Cells X100-X185 in the sheet contain the following insert commands
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Allianz','Allianz','.*(A|a)llianz.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Almenni lífeyrissjóðurinn','Almenni','.*Almenni.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Almennurlífeyrissj. VÍB','AVÍB','.*VÍB.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Arion banki hf.','Arion','.*(A|a)rion.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Bayern','Bayern','(b|B)ayern');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Birta lífeyrissjóður','Birta','.*Birta.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Brú Lífeyrissjóður starfsmanna sveitarfélaga','Brú','.*(B|b)rú.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. Landsbanka og Seðlabanka','Landsbanka og Seðlabanka','Eftirlaunasj.*\\sLandsb(anka|\\.) (og|&) Seðlabanka');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. Sláturfél. Suðurlands','Eftirlaunasj. Sláturfél. Suðurlands','Eftirlaunasj.*(Sláturf(él|.)).*(Suðurlands).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. starfsm. Íslandsb.','Eftirlaunasj. Íslandsb.','Eftirlaunasj(\\.|óður)(\\s|)(s|S)tarfsm(\\.|anna|m\\.)(\\s|)Íslandsb(\\.|anka)(\\s(h|H)f\\.|).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. stm. Glitnis banka','Glitnir','.*Glitn.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. stm. Hafnarfjarðk.','Eftirlaunasj. Hafnarfjarðarkaupstaðar','Eftirlaunasj.*(Hafnarfj).*(kaupst\\.|kaupstaðar|arðk\\.|arðark\\.)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasj. stm. OLÍS','OLÍS','Eftirlaunasj.*(|\\n)(Olí|OLÍ).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasjóður FÍA','EFÍA','(EFÍA|Eftir(-|)launa(-|-\\s|)sj(\\.|\\s|óður)(\\s|\\s\\s|)(atvinnuflugmanna|FÍA))');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasjóður Reykjanesbæjar','Eftirlaunasj. Reykjanesbæjar','Eftirlaunasj.*Reykjanes(-|-\\s|)bæjar');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasjóður slökkviliðsmanna á Keflavíkurflugvelli','Eftirlaunasj. Slökkviliðsmanna á Kef','.*Eftirlaunasj.*(\\s|)slökkvil.* á(\\s|)Keflav.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Eftirlaunasjóður starfsmanna Útvegsbanka Íslands','Eftirlaunasj. Útvegsbanka','Eftirl.*\\s*(starfsm|stm).*\\s*(Ú|ú)tvegsb.*\\s*Ísl.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Festa - lífeyrissjóður','Festa','.*Festa.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Frjálsi lífeyrissjóðurinn','Frjálsi','.*Frjálsi.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Gildi - lífeyrissjóður','Gildi','.*(G|g)ildi.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Íslandsbanki hf.','Íslandsbanki','.*(Í|í)slandsbanki.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Íslenski lífeyrissjóðurinn','Íslenski','.*Íslenski.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Kjölur lífeyrissjóður','Kjölur','(Kjölur lífeyris).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Kvika banki hf.','Kvika','.*(K|k)vika.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Landsbankinn hf.','Landsbankinn','.*(L|l)andsbankinn.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður lækna','Lífeyrissj. Lækna','Lífeyris(-sjóður|sjóður|sj)(\\s|\\.|\\.\\s)(l|L)ækna.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Suðurlands','Lífeyrissj. Suðurlands','Lífeyris(-|)(sj\\.|sjóður )(\\n|\\s|)Suðurlands');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóðurinn Skjöldur','Lífeyrissj. Skjöldur','(Lífeyris).*(sjóðurinn).*(Skjöldur)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóðurinn Eining','Eining','.*Eining.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóðurinn Hlíf','Hlíf','.*Hlíf.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. Akraneskaupstaðar','Lífeyrissj. Akraneskaupstaðar','.*(Akranes(-|-\\s|)kaupst).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. Bolungarvíkur','Lífeyrissj. Bolungarvíkur','(L|l)ífeyrissj.*(\\.|\\s)(Bolungar).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. Eimskipa-félags Ísl.','Lífeyrissj. Eimskipafélag','(Lífeyris).*(sj).*(Eimskipa).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. Fél. ísl. stjstarfsm. á Keflvflugvelli','Lífeyrissj. Félag starfsmanna á Kef flugvelli','Lífeyrissj.*ísl.*stjst.* á Kefl.{0,1}v.{0,4}flugv.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. Neskaupstaðar','Lífeyrissj. Neskaupstaðar','.*((\\.|\\s)Nes(-|)kaup).*(\\.|staðar)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. stm. Húsavíkurk.','Lífeyrissj. Húsavíkurkaupstaðar','.*(Húsa(-|-\\s|)víkur(k|k\\.|-|))(\\.|aupstaðar|bæjar|).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. stm. Reykjavíkurapóteks','Lífeyrissj. Reykjavíkurapóteks','.*Lífeyris(-|)(sj\\.|sjóður )(\\s|)(stm\\.|starfsm\\.|starfsmanna)\\sR(eykjavíkur|vík\\.)(-|-\\s|\\s|)apóteks.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. stm. Vestm.eyjab.','Lífeyrissj. Vestmannaeyjabæjar','Lífeyrissj(\\.|óður\\s)(\\s|)(stm|starfsmanna|starfsm\\.)(\\.\\s|\\s|)Vestm.*eyja(\\s|b\\.|bæjar|-bæjar)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. arkitekta og tæknifr.','Lífeyrissj. Arkitekta og tæknifræðinga','.*(A|a)rkitekta.*(T|t)æknifr.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj. K.E.A.','K.E.A','.*K\\.E\\.A\\..*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissj.verkalfél.Norðurl. v','Lífeyrissj. Verkalfél. Norðurl. V','.*Líf.*(V|v)erkal.*fél\\.(\\sá\\s|\\s|)Norðurl\\. v.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður alþingismanna','Lífeyrissj. Alþingismanna','Lífeyrissj.* alþingis(-\\s|)manna.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Arkitekta','Lífeyrissj. Arkitekta','Lífeyris(-|-\\s|)sjóður Arkitekta');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Austurlands','Lífeyrissj. Austurlands','(L|l)ífeyris(-|)sj(\\.|óður )(\\s|)(Austur(-|-\\s|)lands).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður bænda','Lífeyrissj. Bænda','.*(B|b)ænda.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður bankamanna','Lífeyrissj. Bankamanna','.*Lífeyrissj.*(b|B)anka(-|-\\s|)m.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður blaðamanna','Lífeyrissj. Blaðamanna','.*(B|b)laða(-\\s|)manna.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Félags íslenskra leikara','Lífeyrissj. Félags íslenska leikara','(l|L)ífeyrissj.*(F|f)élags.*ísl.*leikara');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Flugvirkjafél. Íslands','Lífeyrissj. Flugvirkjafélag','(L|l)ífeyrissj.*(\\.|\\s)(Flugvirkja(-f|fé|f.)).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður hjúkrunarfræðinga','Lífeyrissj. Hjúkrunarfræðinga','.*(L|l)íf.+(H|h)júkrunar(-|-\\s|)fræðinga.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Iðnaðarmannafél. Suðurnesja','Lífeyrissj. Iðnaðarmannafél. Suðurnesja','Lífeyrissj.*Iðnaðarm.*Suðurnesja');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður leigubifreiðastjóra','Lífeyrissj. Leigubifreiðastjóra','.*(L|l)eigubifr.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Mjólkursamsölunnar','Lífeyrissj. Mjólkursamsölunnar','(L|l)ífeyrissj.*(\\.|\\s).*(Mjólkur).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Norðurlands','Lífeyrissj. Norðurlands','(L|l)ífeyrissj.*(\\.|\\s)(Norður(-|-\\s|)(lands|))');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður ráðherra','Lífeyrissj. Ráðherra','Lífeyrissj.* ráðherra');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Rangæinga','Lífeyrissj. Rangæinga','Lífeyris(-|)sj(\\.|óður\\s)(\\s|)Rang(\\.|æinga)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður sjómanna','Lífeyrissj. Sjómanna','.*(S|s)jómanna.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsm. Sjóvátryggingafél. ísl.','Lífeyrissj. Sjóvátryggingafél','.*(S|s)jóvá.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna Akureyrarbæjar','Lífeyrissj. Akureyrarbæjar','Lífeyrissj(óður|\\.\\s|\\.)(\\s|\\.|)(stm\\.|starfsm)(anna\\s|\\s|\\.\\s)Akur(-|-\\s|)eyrar(b\\.|bæjar)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna Búnaðarbanka Íslands','Lífeyrissj. Búnaðarbanka','.*(B|b)únaðar.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna Kópavogsbæjar','Lífeyrissj. Kópavogsbæjar','.*Lífeyrissj(óður|\\.)(\\s|)(stm\\.|starfsm\\.|starfsmanna)\\sKópa(-|-\\s|)vogs(b\\.|bæjar|kaupst).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna Reykjavíkurborgar','Lífeyrissj. Reykjavíkurborgar','.*Lífeyris(sjóður|-sjóður|sj\\.)(\\s|\\.|)((S|s)tm\\.\\s|(S|s)tarfsmanna|(S|s)tarfsm\\.)(\\s|)Reykjav(íkurb\\.|b\\.|íkurborgar|\\.).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna ríkisins','Lífeyrissj. ríkisins','(Lífeyrissj.*(starfsm(\\.|anna)|\\.(\\s|)st\\.|\\.\\sst\\.m\\.|stm\\.)\\s(R|r)íkisins|.*LSR.*)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður starfsmanna sveitarfélaga','Lífeyrissj. Sveitarfélaga','Lífeyriss(s|)j(óður|\\.)(\\s|)(s|S)t.*(\\s|\\.|)(s|S)veitarfél(\\.|aga)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður stm. Áburðarverks','Lífeyrissj. Áburðarverksmiðju','.*(Áburðarv(.|e)).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Suðurnesja','Lífeyrissj. Suðurnesja','Lífeyrissj(\\.|óður)(\\s|)Suður(-|-\\s|)nesja');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Tæknifræðingafélags Íslands','Lífeyrissj. Tæknifræðingafélags','Lífeyrissj.*Tæknifr.* Íslands');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Tannlæknafél Ísl','Lífeyrissj. Tannlæknafélags','.*(Tannl|tannl).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður verkafólks í Grindavík','Lífeyrissj. Verkafólks í Grindavík','.*Grindavík.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður verkalýðsfélaga á Suðurlandi','Lífeyrissj. Verkalýðsfélaga á Suðurlandi','Lífeyrissj.*verkal.* á Suðurl(andi|\\.)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður verkfræðinga','Lífsverk','.*(Lífeyrissj).*((V|v)erk.*)fr.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður verslunarmanna','Lífeyrissj. Verslunarmanna','.*((L|l)íf[a-z. óð]*Versl|(L|l)íf[a-z. óð]*versl).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Vestfirðinga','Lífeyrissj. Vestfirðinga','Lífeyrissj(óður|\\.)((\\s|)Vest(-\\s|-\\s\\s|-|)firðinga)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Vestmannaeyja','Lífeyrissj. Vestmannaeyja','.*Lífeyrissj(\\.|óður)(\\s|)Vestm(\\.|(anna(-|-\\s|)eyja)).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóður Vesturlands','Lífeyrissj. Vesturlands','.*Lífeyris(-|)(sj\\.|sjóður)(\\s|)Vestur(-|-\\s|)lands.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóðurinn Framsýn','Framsýn','.*Framsýn.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífeyrissjóðurinn Lífiðn','Lífeyrissj. Lífiðn','(L|l)ífey.*(\\.|\\s)(Lífiðn)+');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífsval','Lífsval','.*Lífsval.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Lífsverk lífeyrissjóður','Lífsverk','.*(L|l)ífsverk.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Sameinaði lífeyrissjóðurinn','Sameinaði','Sameinaði(\\s|)lífeyris(-|-\\s|)sjóðurinn');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Samvinnulífeyrissjóðurinn','Samvinnulífeyrissj.','.*(S|s)amvinnu(-|).*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Séreignalífeyrissjóðurinn','Séreignalífeyrissj.','.*Séreigna.*lífeyris.*sjóðurinn.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Söfnunarsjóður lífeyrisréttinda','Söfnunarsj. Lífeyrisréttinda','(S|s)öfnunarsj(\\.\\s|\\.|óður\\s)(lífeyris(-|)réttinda|)');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Stafir lífeyrissjóður','Stafir','.*Stafir.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Stapi lífeyrissjóður','Stapi','.*(S|s)tapi.*');
INSERT INTO public.fund(fund_name, short_name, regex_keyword)VALUES ('Tryggingasjóður lækna','Tryggingasj. Lækna','.*Trygginga.*sjóður.*lækna.*');